org: gaboooo
service: api-register-login

provider:
  name: aws
  runtime: python3.13
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::044477782735:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_usuarioshack

functions:
  crear:
    handler: auth/register.lambda_handler
    events:
      - http:
          path: auth/register
          method: post
          cors: true
          integration: lambda
  login:
    handler: auth/login.lambda_handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_usuarioshack
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_tokens_accesohack
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST